//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcIsIstek.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOnemliIstekMakinaBakimEntities : DbContext
    {
        public dbOnemliIstekMakinaBakimEntities()
            : base("name=dbOnemliIstekMakinaBakimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbKullanicilar> tbKullanicilar { get; set; }
        public virtual DbSet<tbMakinalar> tbMakinalar { get; set; }
        public virtual DbSet<tbIsIstekleri> tbIsIstekleri { get; set; }
        public virtual DbSet<tbIstekTipleri> tbIstekTipleri { get; set; }
        public virtual DbSet<tbIsIstek_Degerlendirmeleri> tbIsIstek_Degerlendirmeleri { get; set; }
        public virtual DbSet<tbIsIstek_EkliDosyalar> tbIsIstek_EkliDosyalar { get; set; }
        public virtual DbSet<tbLokasyonTanimlari> tbLokasyonTanimlari { get; set; }
        public virtual DbSet<v_Kullanici_Rolleri> v_Kullanici_Rolleri { get; set; }
        public virtual DbSet<tbKategoriler> tbKategoriler { get; set; }
    }
}
