//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcIsIstek.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIsIstek_Degerlendirmeleri
    {
        public int IstekDegerlendirmeID { get; set; }
        public int IsIstekID { get; set; }
        public int DegerlendirenKullaniciID { get; set; }
        public string DeğerlendirmeDurumu { get; set; }
        public Nullable<bool> Onaylı { get; set; }
        public int Puanı { get; set; }
        public string Açıklaması { get; set; }
        public Nullable<int> KaydedenID { get; set; }
        public Nullable<System.DateTime> KayıtZamanı { get; set; }
        public string KayıtBilgisayar { get; set; }
    
        public virtual tbIsIstekleri tbIsIstekleri { get; set; }
    }
}
