//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcIsIstek.App_Data
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class tbIsIstekleri
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public tbIsIstekleri()
		{
			this.tbIsIstek_Degerlendirmeleri = new HashSet<tbIsIstek_Degerlendirmeleri>();
			this.tbIsIstek_EkliDosyalar = new HashSet<tbIsIstek_EkliDosyalar>();
		}

		[Key]
		[ScaffoldColumn(false)]
		public int IsIstekID { get; set; }

		[Required]
		public string KayıtTipi { get; set; }

		[Required]
		public int IstekYapanKullaniciID { get; set; }

		[Required]
		[Index]
		[DisplayName("İstek Tipi")]
		public int IstekTipiID { get; set; }

		[Required]
		[Index]
		[DisplayName("Lokasyon")]
		public int IstekLokasyonID { get; set; }


		[Index]
		[DisplayName("Makina, Ekipman")]
		public Nullable<int> MakinaID { get; set; }

		[Required]
		[DisplayName("Konu")]
		[StringLength(50)]
		public string IstekKonusu { get; set; }


		[DisplayName("Açıklama")]
		public string IstekAçıklaması { get; set; }

		public string IstekAçıklamasıXP { get; set; }

		[Required]
		public string IstekDurumu { get; set; }

		[Required]
		public bool IstekAktif { get; set; }


		[Required]
		public bool Bitti { get; set; }



		public string IstekSonuçAçıklaması { get; set; }
		public string IstekSonuçAçıklamasıXP { get; set; }


		public Nullable<int> MakinaBakimOnarimID { get; set; }
		public Nullable<System.DateTime> SorunGiderilmeZamanı { get; set; }
		public Nullable<System.DateTime> IsIstekBitisZamanı { get; set; }
		public Nullable<System.DateTime> KayıtZamanı { get; set; }


		public string KayıtBilgisayar { get; set; }
		public string SonGuncellemeBilgisayar { get; set; }


		public Nullable<int> SonGuncelleyenID { get; set; }
		public Nullable<System.DateTime> SonGuncellemeZamani { get; set; }



		public virtual tbIstekTipleri tbIstekTipleri { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<tbIsIstek_Degerlendirmeleri> tbIsIstek_Degerlendirmeleri { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<tbIsIstek_EkliDosyalar> tbIsIstek_EkliDosyalar { get; set; }
		public virtual tbLokasyonTanimlari tbLokasyonTanimlari { get; set; }
	}
}
