//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcIsIstek.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKategoriler
    {
        public int KategoriID { get; set; }
        public string Tipi { get; set; }
        public string Kategori { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}
