//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcIsIstek.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKullanicilar
    {
        public int KullaniciID { get; set; }
        public string KullanıcıAdı { get; set; }
        public string Şifresi { get; set; }
        public string AdıSoyadı { get; set; }
        public string Grubu { get; set; }
        public string Tipi { get; set; }
        public bool Adminmi { get; set; }
        public string Ünvanı { get; set; }
        public Nullable<int> LokasyonID { get; set; }
        public Nullable<int> FaaliyetAlaniID { get; set; }
        public string Emaili { get; set; }
        public string CepTelefonu { get; set; }
        public string DahiliTelefonu { get; set; }
        public byte[] Fotografi { get; set; }
        public Nullable<int> UstAmiriID { get; set; }
        public Nullable<bool> SuanSistemde { get; set; }
        public Nullable<bool> DahiliMesajlaşmadaGörünür { get; set; }
        public Nullable<bool> BakımOnarımYapabilir { get; set; }
        public string YerelIPAdresi { get; set; }
        public Nullable<System.DateTime> SonGirişZamanı { get; set; }
        public Nullable<System.DateTime> SonÇikişZamanı { get; set; }
        public bool Aktif { get; set; }
    }
}
