//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcIsIstek.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLokasyonTanimlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLokasyonTanimlari()
        {
            this.tbIsIstekleri = new HashSet<tbIsIstekleri>();
            this.tbMakinalar = new HashSet<tbMakinalar>();
        }
    
        public int LokasyonID { get; set; }
        public string Lokasyon { get; set; }
        public string Şirket { get; set; }
        public string Fabrika { get; set; }
        public string Şube { get; set; }
        public string Departman { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbIsIstekleri> tbIsIstekleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMakinalar> tbMakinalar { get; set; }
    }
}
